/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.theme.editor.inspectors;


/**
 *
 * @author andrea
 */
public class FloatInspector extends javax.swing.JPanel {
    
    float value;
    

    /**
     * Creates new form FloatInspector
     * @param varName
     */
    public FloatInspector(String varName) {
        this(varName,0);
    }
    
    public FloatInspector(String varName,float value) {
        initComponents();
        
        VarnameLabel.setText(varName);
        VarTextField.setText(value+"");
        this.value = value;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VarnameLabel = new javax.swing.JLabel();
        VarTextField = new javax.swing.JFormattedTextField();

        setPreferredSize(new java.awt.Dimension(270, 270));

        VarnameLabel.setText("Varname");

        VarTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        VarTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                VarTextFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VarnameLabel)
                .addGap(18, 18, 18)
                .addComponent(VarTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VarnameLabel)
                    .addComponent(VarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VarTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_VarTextFieldFocusLost
        value = Float.parseFloat(VarTextField.getText());
    }//GEN-LAST:event_VarTextFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField VarTextField;
    private javax.swing.JLabel VarnameLabel;
    // End of variables declaration//GEN-END:variables
}
