/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.theme.editor.inspectors;

import elements.Image;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JCheckBox;

/**
 *
 * @author andrea
 */
public class ImageInspector extends javax.swing.JPanel {
    
    FileInspector path;
    Vector2Inspector origin;
    Vector2Inspector pos;
    Vector2Inspector size;
    ColorInspector color;
    JCheckBox tiled;
    

    /**
     * Creates new form ImageManipolator
     * @param image
     */
    public ImageInspector(Image image) {
        initComponents();
        
        path = new FileInspector("image",image.getImagePath(),"png");
        origin = new Vector2Inspector("Origin",image.getOrigin());
        pos = new Vector2Inspector("Position",image.getPos());
        size = new Vector2Inspector("Size",image.getSize());
        color =  new ColorInspector(image.getColor());
        tiled = new JCheckBox("Tiled",image.getTiled());
        
        
        
        setLayout(new GridBagLayout());
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.anchor = GridBagConstraints.FIRST_LINE_START;
        constraints.weightx = 0.0;
        constraints.gridx=0;
        constraints.gridy=0;
        add(path,constraints);
        
        constraints.weighty = 5.0;
        constraints.gridy++;
        add(origin,constraints);
        
        constraints.gridy++;
        add(pos,constraints);
        
        constraints.gridy++;
        add(size,constraints);
        
        constraints.gridy++;
        add(color,constraints);
        
        constraints.gridy++;
        add(tiled,constraints);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(270, 270));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
