/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.theme.editor.inspectors;

import elements.Text;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author andrea
 */
public class TextInspector extends javax.swing.JPanel {
    
    ColorInspector color;
    FileInspector fontPath;
    FloatInspector fontSize;
    
    Text text;

    /**
     * Creates new form TextInspector
     * @param text
     */
    public TextInspector(Text text) {
        initComponents();
        
        fontPath = new FileInspector("font",text.getFontPath(),"ttf");
        fontSize = new FloatInspector("Font size",text.getFontSize());
        color =  new ColorInspector(text.getColor());
        
        this.text = text;
        
        setLayout(new GridBagLayout());
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.anchor = GridBagConstraints.FIRST_LINE_START;
        constraints.weightx = 0.0;
        constraints.gridx=0;
        constraints.gridy=0;
        add(fontPath,constraints);
        
        constraints.weighty = 5.0;
        constraints.gridy++;
        add(fontSize,constraints);
        
        constraints.gridy++;
        add(color,constraints);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(270, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
