/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.theme.editor;

import elements.Datetime;
import es.theme.editor.inspectors.ImageInspector;
import es.theme.editor.inspectors.TextInspector;
import elements.Image;
import elements.Rating;
import elements.Text;
import elements.Textlist;
import es.theme.editor.objects.View;
import es.theme.editor.objects.ViewObject;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;


/**
 *
 * @author andrea
 */
public class InspectorSection extends javax.swing.JPanel{
    
    ViewObject element;
    View view;
    int index;
    
    GridBagConstraints constraints;
    JPopupMenu popup;

    /**
     * Creates new form GraphicInspectorPanel
     * @param view
     * @param elementIndex
     */
    public InspectorSection(View view,int elementIndex) {
        initComponents();
        
        this.view = view;
        this.index = elementIndex;
        this.element = (ViewObject)view.getElementByIndex(index);
        
        constraints = new GridBagConstraints();
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.anchor = GridBagConstraints.FIRST_LINE_START;
        constraints.weightx = 0.0;
        constraints.gridx=0;
        constraints.gridy=0;
        
        CollapsiblePanel.setLayout(new GridBagLayout());
        AddElementButton.addMouseListener(new MouseListener(){
            @Override
            public void mouseClicked(MouseEvent me) {
                ShowPopup(me);
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mousePressed(MouseEvent me) {
                //ShowPopup(me);
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseReleased(MouseEvent me) {
                //ShowPopup(me);
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseEntered(MouseEvent me) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseExited(MouseEvent me) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
        popup = new JPopupMenu();
        popup.add(AddImageMenuItem);
        popup.add(AddTextMenuItem);
        
        RemoveElementButton.setVisible(element.getExtra());
        
        if(element instanceof Image){
            setInspector(new ImageInspector((Image) element));
        }
        else if(element instanceof Text){
            setInspector(new TextInspector((Text) element));
        }
        
        NameTextField.setText(element.getName());
        
    }
    
    
    
    private void ShowPopup(MouseEvent e){
        popup.show(e.getComponent(), e.getX(), e.getY());
    }
    
    private void setInspector(JPanel panel){
        CollapsiblePanel.add(panel,constraints);
        constraints.weighty = 5.0;
        constraints.gridy++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddImageMenuItem = new javax.swing.JMenuItem();
        AddTextMenuItem = new javax.swing.JMenuItem();
        ExpandButton = new javax.swing.JButton();
        RemoveElementButton = new javax.swing.JButton();
        AddElementButton = new javax.swing.JButton();
        CollapsiblePanel = new org.jdesktop.swingx.JXCollapsiblePane();
        NameTextField = new javax.swing.JTextField();

        AddImageMenuItem.setText("Add new image");
        AddImageMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddImageMenuItemActionPerformed(evt);
            }
        });

        AddTextMenuItem.setText("Add new text");
        AddTextMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTextMenuItemActionPerformed(evt);
            }
        });

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(270, 366));

        ExpandButton.setText("^");
        ExpandButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ExpandButton.setPreferredSize(new java.awt.Dimension(12, 17));
        ExpandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpandButtonActionPerformed(evt);
            }
        });

        RemoveElementButton.setText("-");
        RemoveElementButton.setToolTipText("Remove this element");
        RemoveElementButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        RemoveElementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveElementButtonActionPerformed(evt);
            }
        });

        AddElementButton.setText("+");
        AddElementButton.setToolTipText("Add element...");
        AddElementButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AddElementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddElementButtonActionPerformed(evt);
            }
        });

        CollapsiblePanel.setCollapsed(true);

        NameTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExpandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddElementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemoveElementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(CollapsiblePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpandButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveElementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddElementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CollapsiblePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ExpandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpandButtonActionPerformed
        CollapsiblePanel.setCollapsed(!CollapsiblePanel.isCollapsed());
    }//GEN-LAST:event_ExpandButtonActionPerformed

    private void RemoveElementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveElementButtonActionPerformed
        view.removeExtra(index);
    }//GEN-LAST:event_RemoveElementButtonActionPerformed

    private void AddElementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddElementButtonActionPerformed
    }//GEN-LAST:event_AddElementButtonActionPerformed

    private void AddImageMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddImageMenuItemActionPerformed
        System.out.println("Add image selected");
        Image i = new Image("Image "+view.getElementsCount());
        i.setExtra(true);
        view.addImage(i);
    }//GEN-LAST:event_AddImageMenuItemActionPerformed

    private void AddTextMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTextMenuItemActionPerformed
        System.out.println("Add text selected");
        Text t = new Text("Text "+view.getElementsCount());
        t.setExtra(true);
        view.addText(t);
    }//GEN-LAST:event_AddTextMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddElementButton;
    private javax.swing.JMenuItem AddImageMenuItem;
    private javax.swing.JMenuItem AddTextMenuItem;
    private org.jdesktop.swingx.JXCollapsiblePane CollapsiblePanel;
    private javax.swing.JButton ExpandButton;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JButton RemoveElementButton;
    // End of variables declaration//GEN-END:variables

}
