/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.theme.editor;

import es.theme.editor.objects.View;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;

/**
 *
 * @author andrea
 */
public class InspectorsListPanel extends javax.swing.JPanel {
    
    GridBagConstraints constraints;
    ArrayList<Object> items;
    ArrayList<Boolean> removable;
    EditorFrame mainFrame;

    /**
     * Creates new form InspectorsListPanel
     */
    public InspectorsListPanel() {
        initComponents();
        
        //fixme fix sections 
        setLayout(new GridBagLayout());
        constraints = new GridBagConstraints();
        constraints.fill = GridBagConstraints.HORIZONTAL;
        constraints.anchor = GridBagConstraints.FIRST_LINE_START;
        constraints.weightx = 0.0;
        constraints.weighty = 0.0;
        constraints.gridx = 0;
        
        items = new ArrayList<>();
        removable = new ArrayList<>();
    }
    
    
    public void refresh(View view){
        removeAll();
        InspectorSection section;
        
        constraints.weighty = 0.0;
        constraints.gridy = 0;
        
        for(int i=0;i<view.getElementsCount();i++){
            section = new InspectorSection(view,i);
            add(section);
            constraints.weighty = 5.0;
            constraints.gridy++;
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(270, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
